// ============================================================
// ChemFusion AI — Chemistry Constants & Dummy Data
// All data is static/mocked for V1.0
// ============================================================

import type { Molecule, Chemical, Reaction, AIReactionPrediction, VoiceCommand } from "@/types";

// ─── Element Color Palette ────────────────────────────────────
export const ELEMENT_COLORS: Record<string, string> = {
  H: "#ffffff",
  C: "#404040",
  O: "#e63946",
  N: "#4361ee",
  S: "#f4d03f",
  P: "#f97316",
  Cl: "#2ecc71",
  F: "#00d4ff",
  Br: "#9b2226",
  I: "#7b2d8b",
  Na: "#fcbf49",
  Ca: "#8ecae6",
  Mg: "#95d5b2",
  Fe: "#bc6c25",
  Cu: "#0077b6",
  default: "#8b5cf6",
};

export const ELEMENT_RADII: Record<string, number> = {
  H: 0.25,
  C: 0.35,
  O: 0.33,
  N: 0.32,
  S: 0.40,
  P: 0.38,
  Cl: 0.38,
  F: 0.28,
  default: 0.35,
};

// ─── Sample Molecules ─────────────────────────────────────────
export const MOLECULES: Molecule[] = [
  {
    id: "water",
    name: "Water",
    formula: "H₂O",
    description: "The most essential molecule for life. A polar molecule with unique hydrogen bonding properties.",
    color: "#00d4ff",
    category: "Inorganic",
    molarMass: 18.015,
    boilingPoint: "100°C",
    meltingPoint: "0°C",
    properties: ["Polar solvent", "High heat capacity", "Universal solvent", "Amphoteric"],
    atoms: [
      { id: "O1", element: "Oxygen", symbol: "O", position: [0, 0, 0], radius: 0.33, color: "#e63946", atomicNumber: 8 },
      { id: "H1", element: "Hydrogen", symbol: "H", position: [-0.8, -0.6, 0], radius: 0.25, color: "#ffffff", atomicNumber: 1 },
      { id: "H2", element: "Hydrogen", symbol: "H", position: [0.8, -0.6, 0], radius: 0.25, color: "#ffffff", atomicNumber: 1 },
    ],
    bonds: [
      { from: "O1", to: "H1", type: "single" },
      { from: "O1", to: "H2", type: "single" },
    ],
  },
  {
    id: "methane",
    name: "Methane",
    formula: "CH₄",
    description: "The simplest hydrocarbon and primary component of natural gas. Tetrahedral geometry.",
    color: "#8b5cf6",
    category: "Organic",
    molarMass: 16.043,
    boilingPoint: "-161.5°C",
    meltingPoint: "-182.5°C",
    properties: ["Nonpolar", "Tetrahedral", "Greenhouse gas", "Combustible"],
    atoms: [
      { id: "C1", element: "Carbon", symbol: "C", position: [0, 0, 0], radius: 0.35, color: "#404040", atomicNumber: 6 },
      { id: "H1", element: "Hydrogen", symbol: "H", position: [0.9, 0.9, 0.9], radius: 0.25, color: "#ffffff", atomicNumber: 1 },
      { id: "H2", element: "Hydrogen", symbol: "H", position: [-0.9, -0.9, 0.9], radius: 0.25, color: "#ffffff", atomicNumber: 1 },
      { id: "H3", element: "Hydrogen", symbol: "H", position: [-0.9, 0.9, -0.9], radius: 0.25, color: "#ffffff", atomicNumber: 1 },
      { id: "H4", element: "Hydrogen", symbol: "H", position: [0.9, -0.9, -0.9], radius: 0.25, color: "#ffffff", atomicNumber: 1 },
    ],
    bonds: [
      { from: "C1", to: "H1", type: "single" },
      { from: "C1", to: "H2", type: "single" },
      { from: "C1", to: "H3", type: "single" },
      { from: "C1", to: "H4", type: "single" },
    ],
  },
  {
    id: "benzene",
    name: "Benzene",
    formula: "C₆H₆",
    description: "Aromatic hydrocarbon with a planar ring structure. Foundation of aromatic chemistry.",
    color: "#f97316",
    category: "Aromatic",
    molarMass: 78.114,
    boilingPoint: "80.1°C",
    meltingPoint: "5.5°C",
    properties: ["Aromatic", "Planar ring", "Carcinogenic", "Solvent"],
    atoms: [
      { id: "C1", element: "Carbon", symbol: "C", position: [1.4, 0, 0], radius: 0.35, color: "#404040", atomicNumber: 6 },
      { id: "C2", element: "Carbon", symbol: "C", position: [0.7, 1.21, 0], radius: 0.35, color: "#404040", atomicNumber: 6 },
      { id: "C3", element: "Carbon", symbol: "C", position: [-0.7, 1.21, 0], radius: 0.35, color: "#404040", atomicNumber: 6 },
      { id: "C4", element: "Carbon", symbol: "C", position: [-1.4, 0, 0], radius: 0.35, color: "#404040", atomicNumber: 6 },
      { id: "C5", element: "Carbon", symbol: "C", position: [-0.7, -1.21, 0], radius: 0.35, color: "#404040", atomicNumber: 6 },
      { id: "C6", element: "Carbon", symbol: "C", position: [0.7, -1.21, 0], radius: 0.35, color: "#404040", atomicNumber: 6 },
      { id: "H1", element: "Hydrogen", symbol: "H", position: [2.5, 0, 0], radius: 0.22, color: "#e0e0e0", atomicNumber: 1 },
      { id: "H2", element: "Hydrogen", symbol: "H", position: [1.25, 2.16, 0], radius: 0.22, color: "#e0e0e0", atomicNumber: 1 },
      { id: "H3", element: "Hydrogen", symbol: "H", position: [-1.25, 2.16, 0], radius: 0.22, color: "#e0e0e0", atomicNumber: 1 },
      { id: "H4", element: "Hydrogen", symbol: "H", position: [-2.5, 0, 0], radius: 0.22, color: "#e0e0e0", atomicNumber: 1 },
      { id: "H5", element: "Hydrogen", symbol: "H", position: [-1.25, -2.16, 0], radius: 0.22, color: "#e0e0e0", atomicNumber: 1 },
      { id: "H6", element: "Hydrogen", symbol: "H", position: [1.25, -2.16, 0], radius: 0.22, color: "#e0e0e0", atomicNumber: 1 },
    ],
    bonds: [
      { from: "C1", to: "C2", type: "aromatic" },
      { from: "C2", to: "C3", type: "aromatic" },
      { from: "C3", to: "C4", type: "aromatic" },
      { from: "C4", to: "C5", type: "aromatic" },
      { from: "C5", to: "C6", type: "aromatic" },
      { from: "C6", to: "C1", type: "aromatic" },
      { from: "C1", to: "H1", type: "single" },
      { from: "C2", to: "H2", type: "single" },
      { from: "C3", to: "H3", type: "single" },
      { from: "C4", to: "H4", type: "single" },
      { from: "C5", to: "H5", type: "single" },
      { from: "C6", to: "H6", type: "single" },
    ],
  },
  {
    id: "ethanol",
    name: "Ethanol",
    formula: "C₂H₅OH",
    description: "Common alcohol found in beverages and used as a solvent and fuel. Contains a hydroxyl group.",
    color: "#10b981",
    category: "Organic",
    molarMass: 46.069,
    boilingPoint: "78.4°C",
    meltingPoint: "-114.1°C",
    properties: ["Polar", "Hydrogen bonding", "Miscible with water", "Fuel additive"],
    atoms: [
      { id: "C1", element: "Carbon", symbol: "C", position: [-0.9, 0, 0], radius: 0.35, color: "#404040", atomicNumber: 6 },
      { id: "C2", element: "Carbon", symbol: "C", position: [0.9, 0, 0], radius: 0.35, color: "#404040", atomicNumber: 6 },
      { id: "O1", element: "Oxygen", symbol: "O", position: [2.1, 0.8, 0], radius: 0.33, color: "#e63946", atomicNumber: 8 },
      { id: "H1", element: "Hydrogen", symbol: "H", position: [-0.9, 1.1, 0.7], radius: 0.25, color: "#ffffff", atomicNumber: 1 },
      { id: "H2", element: "Hydrogen", symbol: "H", position: [-0.9, 1.1, -0.7], radius: 0.25, color: "#ffffff", atomicNumber: 1 },
      { id: "H3", element: "Hydrogen", symbol: "H", position: [-2.0, -0.5, 0], radius: 0.25, color: "#ffffff", atomicNumber: 1 },
      { id: "H4", element: "Hydrogen", symbol: "H", position: [0.9, -1.1, 0.7], radius: 0.25, color: "#ffffff", atomicNumber: 1 },
      { id: "H5", element: "Hydrogen", symbol: "H", position: [0.9, -1.1, -0.7], radius: 0.25, color: "#ffffff", atomicNumber: 1 },
      { id: "H6", element: "Hydrogen", symbol: "H", position: [2.9, 0.2, 0], radius: 0.25, color: "#ffffff", atomicNumber: 1 },
    ],
    bonds: [
      { from: "C1", to: "C2", type: "single" },
      { from: "C2", to: "O1", type: "single" },
      { from: "C1", to: "H1", type: "single" },
      { from: "C1", to: "H2", type: "single" },
      { from: "C1", to: "H3", type: "single" },
      { from: "C2", to: "H4", type: "single" },
      { from: "C2", to: "H5", type: "single" },
      { from: "O1", to: "H6", type: "single" },
    ],
  },
  {
    id: "ammonia",
    name: "Ammonia",
    formula: "NH₃",
    description: "Pungent gas used in fertilizers and cleaning products. Trigonal pyramidal structure.",
    color: "#ec4899",
    category: "Inorganic",
    molarMass: 17.031,
    boilingPoint: "-33.34°C",
    meltingPoint: "-77.73°C",
    properties: ["Polar", "Pungent odor", "Weak base", "Hydrogen bonding"],
    atoms: [
      { id: "N1", element: "Nitrogen", symbol: "N", position: [0, 0, 0], radius: 0.32, color: "#4361ee", atomicNumber: 7 },
      { id: "H1", element: "Hydrogen", symbol: "H", position: [1.0, 0, 0], radius: 0.25, color: "#ffffff", atomicNumber: 1 },
      { id: "H2", element: "Hydrogen", symbol: "H", position: [-0.5, 0.87, 0], radius: 0.25, color: "#ffffff", atomicNumber: 1 },
      { id: "H3", element: "Hydrogen", symbol: "H", position: [-0.5, -0.87, 0], radius: 0.25, color: "#ffffff", atomicNumber: 1 },
    ],
    bonds: [
      { from: "N1", to: "H1", type: "single" },
      { from: "N1", to: "H2", type: "single" },
      { from: "N1", to: "H3", type: "single" },
    ],
  },
  {
    id: "carbon_dioxide",
    name: "Carbon Dioxide",
    formula: "CO₂",
    description: "Greenhouse gas produced during combustion and respiration. Linear molecular geometry.",
    color: "#f59e0b",
    category: "Inorganic",
    molarMass: 44.009,
    boilingPoint: "-78.46°C",
    meltingPoint: "-56.6°C",
    properties: ["Linear", "Nonpolar", "Greenhouse gas", "Sublimes from solid"],
    atoms: [
      { id: "C1", element: "Carbon", symbol: "C", position: [0, 0, 0], radius: 0.35, color: "#404040", atomicNumber: 6 },
      { id: "O1", element: "Oxygen", symbol: "O", position: [-1.2, 0, 0], radius: 0.33, color: "#e63946", atomicNumber: 8 },
      { id: "O2", element: "Oxygen", symbol: "O", position: [1.2, 0, 0], radius: 0.33, color: "#e63946", atomicNumber: 8 },
    ],
    bonds: [
      { from: "C1", to: "O1", type: "double" },
      { from: "C1", to: "O2", type: "double" },
    ],
  },
  {
    id: "acetic_acid",
    name: "Acetic Acid",
    formula: "CH₃COOH",
    description: "Weak organic acid in vinegar. Important in chemistry and food industry.",
    color: "#ef4444",
    category: "Organic",
    molarMass: 60.052,
    boilingPoint: "118.1°C",
    meltingPoint: "16.6°C",
    properties: ["Weak acid", "Vinegar component", "Hydrogen bonding", "Polar"],
    atoms: [
      { id: "C1", element: "Carbon", symbol: "C", position: [-1.0, 0, 0], radius: 0.35, color: "#404040", atomicNumber: 6 },
      { id: "C2", element: "Carbon", symbol: "C", position: [1.0, 0, 0], radius: 0.35, color: "#404040", atomicNumber: 6 },
      { id: "O1", element: "Oxygen", symbol: "O", position: [2.2, 0.8, 0], radius: 0.33, color: "#e63946", atomicNumber: 8 },
      { id: "O2", element: "Oxygen", symbol: "O", position: [1.0, -1.2, 0], radius: 0.33, color: "#e63946", atomicNumber: 8 },
      { id: "H1", element: "Hydrogen", symbol: "H", position: [-1.0, 1.1, 0.7], radius: 0.25, color: "#ffffff", atomicNumber: 1 },
      { id: "H2", element: "Hydrogen", symbol: "H", position: [-1.0, 1.1, -0.7], radius: 0.25, color: "#ffffff", atomicNumber: 1 },
      { id: "H3", element: "Hydrogen", symbol: "H", position: [-2.1, -0.5, 0], radius: 0.25, color: "#ffffff", atomicNumber: 1 },
      { id: "H4", element: "Hydrogen", symbol: "H", position: [2.8, 0.2, 0], radius: 0.25, color: "#ffffff", atomicNumber: 1 },
    ],
    bonds: [
      { from: "C1", to: "C2", type: "single" },
      { from: "C2", to: "O1", type: "single" },
      { from: "C2", to: "O2", type: "double" },
      { from: "C1", to: "H1", type: "single" },
      { from: "C1", to: "H2", type: "single" },
      { from: "C1", to: "H3", type: "single" },
      { from: "O1", to: "H4", type: "single" },
    ],
  },
  {
    id: "glucose",
    name: "Glucose",
    formula: "C₆H₁₂O₆",
    description: "Simple sugar and primary source of energy for cells. Most abundant monosaccharide.",
    color: "#06b6d4",
    category: "Organic",
    molarMass: 180.156,
    boilingPoint: "~400°C",
    meltingPoint: "146°C",
    properties: ["Aldohexose", "Sweet taste", "Soluble in water", "Energy source"],
    atoms: [
      { id: "C1", element: "Carbon", symbol: "C", position: [0, 0, 0], radius: 0.35, color: "#404040", atomicNumber: 6 },
      { id: "C2", element: "Carbon", symbol: "C", position: [1.5, 0.5, 0], radius: 0.35, color: "#404040", atomicNumber: 6 },
      { id: "C3", element: "Carbon", symbol: "C", position: [2.0, 2.0, 0], radius: 0.35, color: "#404040", atomicNumber: 6 },
      { id: "C4", element: "Carbon", symbol: "C", position: [1.0, 3.2, 0], radius: 0.35, color: "#404040", atomicNumber: 6 },
      { id: "C5", element: "Carbon", symbol: "C", position: [-0.5, 2.8, 0], radius: 0.35, color: "#404040", atomicNumber: 6 },
      { id: "C6", element: "Carbon", symbol: "C", position: [-1.0, 1.4, 0], radius: 0.35, color: "#404040", atomicNumber: 6 },
      { id: "O1", element: "Oxygen", symbol: "O", position: [0.5, -1.2, 0], radius: 0.33, color: "#e63946", atomicNumber: 8 },
      { id: "O2", element: "Oxygen", symbol: "O", position: [2.5, 1.0, 1.0], radius: 0.33, color: "#e63946", atomicNumber: 8 },
      { id: "O3", element: "Oxygen", symbol: "O", position: [3.3, 2.3, 0], radius: 0.33, color: "#e63946", atomicNumber: 8 },
      { id: "O4", element: "Oxygen", symbol: "O", position: [1.5, 4.5, 0], radius: 0.33, color: "#e63946", atomicNumber: 8 },
      { id: "O5", element: "Oxygen", symbol: "O", position: [-1.2, 3.9, 0], radius: 0.33, color: "#e63946", atomicNumber: 8 },
      { id: "O6", element: "Oxygen", symbol: "O", position: [-2.3, 1.0, 0], radius: 0.33, color: "#e63946", atomicNumber: 8 },
      { id: "H1", element: "Hydrogen", symbol: "H", position: [0, -1.8, 0], radius: 0.25, color: "#ffffff", atomicNumber: 1 },
    ],
    bonds: [
      { from: "C1", to: "C2", type: "single" },
      { from: "C2", to: "C3", type: "single" },
      { from: "C3", to: "C4", type: "single" },
      { from: "C4", to: "C5", type: "single" },
      { from: "C5", to: "C6", type: "single" },
      { from: "C1", to: "O1", type: "double" },
      { from: "C2", to: "O2", type: "single" },
      { from: "C3", to: "O3", type: "single" },
      { from: "C4", to: "O4", type: "single" },
      { from: "C5", to: "O5", type: "single" },
      { from: "C6", to: "O6", type: "single" },
    ],
  },
  {
    id: "sulfuric_acid",
    name: "Sulfuric Acid",
    formula: "H₂SO₄",
    description: "Strong diprotic acid. One of the most important industrial chemicals.",
    color: "#f97316",
    category: "Inorganic",
    molarMass: 98.079,
    boilingPoint: "337°C",
    meltingPoint: "10.31°C",
    properties: ["Strong acid", "Highly corrosive", "Hygroscopic", "Dehydrating"],
    atoms: [
      { id: "S1", element: "Sulfur", symbol: "S", position: [0, 0, 0], radius: 0.40, color: "#f4d03f", atomicNumber: 16 },
      { id: "O1", element: "Oxygen", symbol: "O", position: [-1.5, 0, 0], radius: 0.33, color: "#e63946", atomicNumber: 8 },
      { id: "O2", element: "Oxygen", symbol: "O", position: [1.5, 0, 0], radius: 0.33, color: "#e63946", atomicNumber: 8 },
      { id: "O3", element: "Oxygen", symbol: "O", position: [0, 1.5, 0], radius: 0.33, color: "#e63946", atomicNumber: 8 },
      { id: "O4", element: "Oxygen", symbol: "O", position: [0, -1.5, 0], radius: 0.33, color: "#e63946", atomicNumber: 8 },
      { id: "H1", element: "Hydrogen", symbol: "H", position: [0.7, 2.0, 0], radius: 0.25, color: "#ffffff", atomicNumber: 1 },
      { id: "H2", element: "Hydrogen", symbol: "H", position: [-0.7, -2.0, 0], radius: 0.25, color: "#ffffff", atomicNumber: 1 },
    ],
    bonds: [
      { from: "S1", to: "O1", type: "double" },
      { from: "S1", to: "O2", type: "double" },
      { from: "S1", to: "O3", type: "single" },
      { from: "S1", to: "O4", type: "single" },
      { from: "O3", to: "H1", type: "single" },
      { from: "O4", to: "H2", type: "single" },
    ],
  },
];

// ─── Lab Chemicals ────────────────────────────────────────────
export const LAB_CHEMICALS: Chemical[] = [
  { id: "hcl", name: "Hydrochloric Acid", formula: "HCl", color: "#fbbf24", state: "liquid", hazard: "danger", description: "Strong acid, highly corrosive" },
  { id: "naoh", name: "Sodium Hydroxide", formula: "NaOH", color: "#a78bfa", state: "solid", hazard: "danger", description: "Strong base, caustic" },
  { id: "h2so4", name: "Sulfuric Acid", formula: "H₂SO₄", color: "#f59e0b", state: "liquid", hazard: "danger", description: "Concentrated strong acid" },
  { id: "nacl", name: "Sodium Chloride", formula: "NaCl", color: "#94a3b8", state: "solid", hazard: "safe", description: "Common table salt" },
  { id: "h2o2", name: "Hydrogen Peroxide", formula: "H₂O₂", color: "#38bdf8", state: "liquid", hazard: "caution", description: "Oxidizing agent" },
  { id: "mgso4", name: "Magnesium Sulfate", formula: "MgSO₄", color: "#86efac", state: "solid", hazard: "safe", description: "Epsom salt" },
  { id: "cuso4", name: "Copper Sulfate", formula: "CuSO₄", color: "#0ea5e9", state: "solid", hazard: "caution", description: "Bright blue crystals" },
  { id: "kmno4", name: "Potassium Permanganate", formula: "KMnO₄", color: "#7c3aed", state: "solid", hazard: "caution", description: "Strong oxidizer" },
  { id: "na2co3", name: "Sodium Carbonate", formula: "Na₂CO₃", color: "#d1d5db", state: "solid", hazard: "safe", description: "Washing soda" },
  { id: "phenolphthalein", name: "Phenolphthalein", formula: "C₂₀H₁₄O₄", color: "#fce7f3", state: "liquid", hazard: "caution", description: "pH indicator" },
];

// ─── Lab Reactions ────────────────────────────────────────────
export const LAB_REACTIONS: Reaction[] = [
  {
    id: "r1",
    reactants: ["hcl", "naoh"],
    products: ["NaCl", "H₂O"],
    equation: "HCl + NaOH → NaCl + H₂O",
    type: "Neutralization",
    observation: "Temperature rises sharply. Indicator changes color. pH reaches 7.",
    safetyWarning: "⚠️ Strong acid + strong base reaction. Wear gloves and goggles.",
    energyChange: "exothermic",
    color: "#fbbf24",
  },
  {
    id: "r2",
    reactants: ["hcl", "na2co3"],
    products: ["NaCl", "H₂O", "CO₂"],
    equation: "2HCl + Na₂CO₃ → 2NaCl + H₂O + CO₂↑",
    type: "Double Displacement",
    observation: "Vigorous bubbling (CO₂ gas). Fizzing reaction.",
    safetyWarning: "⚠️ CO₂ gas produced. Ensure ventilation.",
    energyChange: "exothermic",
    color: "#38bdf8",
    gas: "CO₂",
  },
  {
    id: "r3",
    reactants: ["cuso4", "naoh"],
    products: ["Cu(OH)₂", "Na₂SO₄"],
    equation: "CuSO₄ + 2NaOH → Cu(OH)₂↓ + Na₂SO₄",
    type: "Precipitation",
    observation: "Blue precipitate forms immediately.",
    safetyWarning: "⚠️ Copper compounds are toxic. Dispose properly.",
    energyChange: "neutral",
    color: "#0ea5e9",
    precipitate: "Cu(OH)₂",
  },
  {
    id: "r4",
    reactants: ["h2o2", "kmno4"],
    products: ["O₂", "H₂O", "MnO₂"],
    equation: "5H₂O₂ + 2KMnO₄ + 3H₂SO₄ → 2MnSO₄ + K₂SO₄ + 8H₂O + 5O₂",
    type: "Redox",
    observation: "Purple color disappears. Oxygen bubbles evolve rapidly.",
    safetyWarning: "⚠️ Strong oxidizer reaction. No flames nearby.",
    energyChange: "exothermic",
    color: "#7c3aed",
    gas: "O₂",
  },
];

// ─── AI Reaction Predictions (Mocked) ─────────────────────────
export const MOCK_PREDICTIONS: Record<string, AIReactionPrediction> = {
  default: {
    input: "",
    balancedEquation: "2H₂ + O₂ → 2H₂O",
    products: ["Water (H₂O)"],
    reactionType: "Synthesis / Combustion",
    industrialUses: ["Rocket fuel combustion", "Fuel cells", "Welding"],
    energyChange: "exothermic",
    enthalpy: "ΔH = −483.6 kJ/mol",
    mechanism: "Free radical chain mechanism involving H• and OH• intermediates.",
    conditions: ["Spark or ignition", "Room temperature", "High pressure in industrial use"],
    safetyNotes: ["Highly flammable gas mixture", "Risk of explosion", "Use in well-ventilated areas"],
  },
};

export const AI_PREDICTION_TEMPLATES: AIReactionPrediction[] = [
  {
    input: "H₂ + O₂",
    balancedEquation: "2H₂ + O₂ → 2H₂O",
    products: ["Water (H₂O)"],
    reactionType: "Synthesis / Combustion",
    industrialUses: ["Rocket propulsion", "Hydrogen fuel cells", "Welding (oxy-hydrogen)"],
    energyChange: "exothermic",
    enthalpy: "ΔH = −483.6 kJ/mol",
    mechanism: "Free radical chain mechanism via H• and OH• intermediates at high temperatures.",
    conditions: ["Ignition source (spark)", "Stoichiometric mixture", "Elevated pressure"],
    safetyNotes: ["Highly explosive mixture", "Keep away from flames", "Store hydrogen in sealed containers"],
  },
  {
    input: "CH₄ + O₂",
    balancedEquation: "CH₄ + 2O₂ → CO₂ + 2H₂O",
    products: ["Carbon dioxide (CO₂)", "Water (H₂O)"],
    reactionType: "Combustion",
    industrialUses: ["Natural gas power plants", "Heating systems", "Methanol production"],
    energyChange: "exothermic",
    enthalpy: "ΔH = −890.3 kJ/mol",
    mechanism: "Free radical chain mechanism; CH₄ undergoes hydrogen abstraction to form methyl radicals.",
    conditions: ["Temperature > 500°C", "Oxygen-rich environment", "Catalyst optional"],
    safetyNotes: ["Combustible gas", "CO₂ greenhouse gas byproduct", "Ensure complete combustion to avoid CO"],
  },
  {
    input: "NaOH + HCl",
    balancedEquation: "NaOH + HCl → NaCl + H₂O",
    products: ["Sodium chloride (NaCl)", "Water (H₂O)"],
    reactionType: "Acid-Base Neutralization",
    industrialUses: ["pH regulation in water treatment", "Soap manufacturing", "Pharmaceutical synthesis"],
    energyChange: "exothermic",
    enthalpy: "ΔH = −57.1 kJ/mol",
    mechanism: "Proton transfer: H⁺ from HCl combines with OH⁻ from NaOH to form water.",
    conditions: ["Aqueous solution", "Room temperature", "No catalyst needed"],
    safetyNotes: ["Both reactants are corrosive", "Generates heat — dilute carefully", "Wear PPE"],
  },
  {
    input: "Fe + O₂",
    balancedEquation: "4Fe + 3O₂ → 2Fe₂O₃",
    products: ["Iron(III) oxide (Fe₂O₃) — Rust"],
    reactionType: "Oxidation",
    industrialUses: ["Iron smelting by-product", "Red pigments", "Magnetic materials"],
    energyChange: "exothermic",
    enthalpy: "ΔH = −824.2 kJ/mol",
    mechanism: "Electrochemical oxidation: Fe loses electrons, O₂ gains electrons. Accelerated by moisture.",
    conditions: ["Presence of moisture", "Room temperature (slow)", "Elevated temperature (fast)"],
    safetyNotes: ["Generates iron oxide dust — avoid inhaling", "Structural weakening of iron components"],
  },
  {
    input: "N₂ + H₂",
    balancedEquation: "N₂ + 3H₂ → 2NH₃",
    products: ["Ammonia (NH₃)"],
    reactionType: "Synthesis (Haber Process)",
    industrialUses: ["Fertilizer production (80%)", "Explosives manufacturing", "Refrigerant (R-717)"],
    energyChange: "exothermic",
    enthalpy: "ΔH = −92.4 kJ/mol",
    mechanism: "Catalytic surface reaction: N₂ and H₂ adsorb on iron catalyst, dissociate, and recombine as NH₃.",
    conditions: ["400–500°C", "150–300 atm pressure", "Iron catalyst with K₂O, Al₂O₃ promoters"],
    safetyNotes: ["Ammonia is toxic and corrosive", "High-pressure industrial process", "Ensure proper ventilation"],
  },
  {
    input: "Na + O₂",
    balancedEquation: "2Na + O₂ → Na₂O₂",
    products: ["Sodium peroxide (Na₂O₂)"],
    reactionType: "Oxidation / Combination",
    industrialUses: ["Oxygen generation systems", "Bleaching agents", "Water purification"],
    energyChange: "exothermic",
    enthalpy: "ΔH = −505 kJ/mol",
    mechanism: "Sodium metal loses electrons (oxidation) and oxygen gains electrons (reduction). Forms ionic compound with peroxide ion (O₂²⁻).",
    conditions: ["Excess oxygen", "Room temperature (slow)", "Elevated temperature (faster)", "Dry conditions required"],
    safetyNotes: ["Sodium is highly reactive — stored under mineral oil", "Reacts violently with water", "Sodium peroxide reacts with moisture to produce oxygen and heat"],
  },
  {
    input: "HCl + NaOH",
    balancedEquation: "HCl + NaOH → NaCl + H₂O",
    products: ["Sodium chloride (NaCl)", "Water (H₂O)"],
    reactionType: "Acid-Base Neutralization",
    industrialUses: ["pH control", "Salt production", "Water treatment"],
    energyChange: "exothermic",
    enthalpy: "ΔH = −57.1 kJ/mol",
    mechanism: "Proton transfer: H⁺ transfers from HCl to OH⁻ forming water and salt ions.",
    conditions: ["Aqueous solution", "Room temperature"],
    safetyNotes: ["Both reactants are corrosive", "Wear safety goggles and gloves"],
  },
  {
    input: "C + O₂",
    balancedEquation: "C + O₂ → CO₂",
    products: ["Carbon dioxide (CO₂)"],
    reactionType: "Combustion",
    industrialUses: ["Energy production", "Greenhouse gas", "Dry ice production"],
    energyChange: "exothermic",
    enthalpy: "ΔH = −393.5 kJ/mol",
    mechanism: "Complete combustion of carbon to CO₂; each carbon atom bonds with two oxygen atoms.",
    conditions: ["Temperature > 700°C", "Excess oxygen"],
    safetyNotes: ["CO₂ is a greenhouse gas", "Complete combustion required to avoid CO formation"],
  },
  {
    input: "H₂O₂",
    balancedEquation: "2H₂O₂ → 2H₂O + O₂",
    products: ["Water (H₂O)", "Oxygen (O₂)"],
    reactionType: "Decomposition",
    industrialUses: ["Disinfectant", "Propellant", "Bleaching"],
    energyChange: "exothermic",
    enthalpy: "ΔH = −196.1 kJ/mol",
    mechanism: "Hydrogen peroxide spontaneously decomposes into water and oxygen gas.",
    conditions: ["Room temperature (slow)", "Catalyst MnO₂ (fast)", "Light accelerates decomposition"],
    safetyNotes: ["Hydrogen peroxide can decompose explosively if concentrated", "Handle dilute solutions carefully"],
  },
  {
    input: "CaCO₃",
    balancedEquation: "CaCO₃ → CaO + CO₂",
    products: ["Calcium oxide (CaO) — Quicklime", "Carbon dioxide (CO₂)"],
    reactionType: "Thermal Decomposition",
    industrialUses: ["Cement production", "Limestone calcination", "Quicklime production"],
    energyChange: "endothermic",
    enthalpy: "ΔH = +178 kJ/mol",
    mechanism: "Heat breaks C-O bonds in carbonate, releasing CO₂ gas and leaving CaO.",
    conditions: ["Temperature > 825°C", "Industrial furnaces"],
    safetyNotes: ["Requires high heat", "CO₂ emissions", "CaO reacts violently with water"],
  },
  {
    input: "Mg + O₂",
    balancedEquation: "2Mg + O₂ → 2MgO",
    products: ["Magnesium oxide (MgO)"],
    reactionType: "Oxidation / Combination",
    industrialUses: ["Metal alloys", "Refractory materials", "Pharmaceutical"],
    energyChange: "exothermic",
    enthalpy: "ΔH = −1204 kJ/mol",
    mechanism: "Magnesium metal loses electrons to oxygen, forming ionic MgO compound.",
    conditions: ["Ignition source (heat/spark)", "Room temperature thereafter"],
    safetyNotes: ["Magnesium burns with intense white light", "Wear protective equipment", "Use sand/dry powder to extinguish"],
  },
  {
    input: "Cu + O₂",
    balancedEquation: "2Cu + O₂ → 2CuO",
    products: ["Copper(II) oxide (CuO)"],
    reactionType: "Oxidation",
    industrialUses: ["Pigments", "Semiconductor materials", "Catalysts"],
    energyChange: "exothermic",
    enthalpy: "ΔH = −310.6 kJ/mol",
    mechanism: "Copper oxidizes to Cu²⁺ and combines with oxygen forming black CuO.",
    conditions: ["Heating copper wire/foil", "Temperature > 800°C"],
    safetyNotes: ["Produces black powder (CuO)", "Avoid inhaling dust"],
  },
  {
    input: "Cl₂ + H₂",
    balancedEquation: "Cl₂ + H₂ → 2HCl",
    products: ["Hydrogen chloride (HCl)"],
    reactionType: "Synthesis / Combination",
    industrialUses: ["Hydrochloric acid production", "Organic synthesis", "Metal processing"],
    energyChange: "exothermic",
    enthalpy: "ΔH = −184.6 kJ/mol",
    mechanism: "Radical chain reaction with UV light initiation, forming HCl molecules.",
    conditions: ["UV light or heat > 250°C", "Explosion risk in sunlight"],
    safetyNotes: ["Highly explosive mixture", "Keep away from light and heat", "Both gases are toxic"],
  },
  {
    input: "S + O₂",
    balancedEquation: "S + O₂ → SO₂",
    products: ["Sulfur dioxide (SO₂)"],
    reactionType: "Combustion",
    industrialUses: ["Sulfuric acid production", "Disinfectant", "Preservative"],
    energyChange: "exothermic",
    enthalpy: "ΔH = −296.8 kJ/mol",
    mechanism: "Sulfur burns in oxygen to form SO₂ gas (choking odor).",
    conditions: ["Temperature > 250°C", "Ignition source"],
    safetyNotes: ["SO₂ is toxic and irritating", "Avoid breathing fumes", "Primary air pollutant"],
  },
  {
    input: "P + O₂",
    balancedEquation: "4P + 5O₂ → 2P₂O₅",
    products: ["Phosphorus pentoxide (P₂O₅)"],
    reactionType: "Combustion",
    industrialUses: ["Dehydrating agent", "Phosphoric acid production", "Semiconductor doping"],
    energyChange: "exothermic",
    enthalpy: "ΔH = −3009.6 kJ/mol (for 4 moles P)",
    mechanism: "White phosphorus ignites spontaneously in oxygen at room temperature.",
    conditions: ["Room temperature (spontaneous)", "Air/oxygen present"],
    safetyNotes: ["White phosphorus is spontaneously flammable", "Store under water", "Extremely dangerous"],
  },
  {
    input: "AgNO₃ + NaCl",
    balancedEquation: "AgNO₃ + NaCl → AgCl↓ + NaNO₃",
    products: ["Silver chloride (AgCl) — white precipitate", "Sodium nitrate (NaNO₃)"],
    reactionType: "Precipitation",
    industrialUses: ["Photography (silver halides)", "Qualitative analysis", "Sensor production"],
    energyChange: "exothermic",
    enthalpy: "ΔH = −65.5 kJ/mol",
    mechanism: "Silver ions precipitate with chloride ions forming insoluble white AgCl solid.",
    conditions: ["Aqueous solution", "Room temperature"],
    safetyNotes: ["AgCl is light-sensitive (darkens)", "Silver compounds can stain skin"],
  },
  {
    input: "NH₃ + HCl",
    balancedEquation: "NH₃ + HCl → NH₄Cl",
    products: ["Ammonium chloride (NH₄Cl)"],
    reactionType: "Acid-Base Neutralization",
    industrialUses: ["Dry cells (batteries)", "Fertilizer production", "Textile dyeing"],
    energyChange: "exothermic",
    enthalpy: "ΔH = −52.2 kJ/mol",
    mechanism: "Ammonia accepts a proton from HCl, forming ammonium ion and chloride ion.",
    conditions: ["Aqueous or gas phase", "Room temperature"],
    safetyNotes: ["Both reactants are toxic gases", "Visible smoke forms when gases mix"],
  },
  {
    input: "Zn + HCl",
    balancedEquation: "Zn + 2HCl → ZnCl₂ + H₂↑",
    products: ["Zinc chloride (ZnCl₂)", "Hydrogen gas (H₂)"],
    reactionType: "Displacement / Acid-Metal",
    industrialUses: ["Hydrogen gas generation", "Galvanization byproduct", "Chemical synthesis"],
    energyChange: "exothermic",
    enthalpy: "ΔH = −152 kJ/mol",
    mechanism: "Zinc displaces hydrogen from HCl; Zn loses electrons, H⁺ gains electrons.",
    conditions: ["Room temperature", "Dilute HCl"],
    safetyNotes: ["H₂ gas is flammable", "Reaction is vigorous — handle carefully", "Acid is corrosive"],
  },
  {
    input: "Fe + CuSO₄",
    balancedEquation: "Fe + CuSO₄ → FeSO₄ + Cu",
    products: ["Iron(II) sulfate (FeSO₄)", "Copper metal (Cu) — red deposit"],
    reactionType: "Displacement / Redox",
    industrialUses: ["Copper extraction", "Redox reactions demo", "Metal recovery"],
    energyChange: "exothermic",
    enthalpy: "ΔH = −67.5 kJ/mol",
    mechanism: "Iron is more reactive than copper; Fe loses electrons, Cu²⁺ gains electrons.",
    conditions: ["Room temperature", "Aqueous CuSO₄"],
    safetyNotes: ["Solution changes from blue to colorless", "Hot surface forms on reaction"],
  },
  {
    input: "NaCl + AgNO₃",
    balancedEquation: "NaCl + AgNO₃ → AgCl↓ + NaNO₃",
    products: ["Silver chloride precipitate (AgCl)", "Sodium nitrate (NaNO₃)"],
    reactionType: "Precipitation",
    industrialUses: ["Qualitative analysis", "Photography", "Analytical testing"],
    energyChange: "exothermic",
    enthalpy: "ΔH = −65.5 kJ/mol",
    mechanism: "Ag⁺ ions combine with Cl⁻ ions forming white insoluble AgCl precipitate.",
    conditions: ["Aqueous solution", "Room temperature"],
    safetyNotes: ["Forms white precipitate immediately", "AgCl is photosensitive"],
  },
];

// ─── AI Tutor Responses (Mocked) ──────────────────────────────
export const TUTOR_RESPONSES: Record<string, string> = {
  default: "That's a great chemistry question! In chemistry, we study matter and the changes it undergoes. Could you be more specific about what topic you'd like to explore?",
  "what is a mole": "A mole is a unit of measurement in chemistry equal to 6.022 × 10²³ entities (Avogadro's number). Think of it like a 'dozen' but for atoms! 1 mole of carbon = 12 grams = 602,200,000,000,000,000,000,000 atoms.",
  "explain oxidation": "Oxidation is the loss of electrons from an atom or molecule. Remember: **OIL RIG** — Oxidation Is Loss, Reduction Is Gain. Example: Fe → Fe²⁺ + 2e⁻ (iron oxidizes when it rusts).",
  "what is entropy": "Entropy (S) measures disorder or randomness in a system. Higher entropy = more disordered. Ice (ordered) → Water (less ordered) → Steam (most disordered). The 2nd Law of Thermodynamics states entropy of an isolated system always increases.",
  "ph scale": "The pH scale ranges from 0-14: pH < 7 = Acid (lemon juice pH 2), pH = 7 = Neutral (pure water), pH > 7 = Base (baking soda pH 9). pH = -log[H⁺]. A difference of 1 pH unit = 10× difference in H⁺ concentration!",
  "covalent bond": "A covalent bond forms when two atoms **share** electrons. Example: H₂O — oxygen shares one pair of electrons with each hydrogen. Polar covalent bonds occur when electrons aren't shared equally (like in water). Nonpolar when shared equally (like in H₂).",
  "ionic bond": "An ionic bond forms when electrons are **transferred** from one atom to another, creating oppositely charged ions that attract each other. Example: Na gives its electron to Cl → Na⁺ + Cl⁻ → NaCl (table salt). These bonds are strong and form crystalline structures.",
  "periodic table": "The periodic table organizes 118 elements by atomic number and chemical properties. **Groups** (columns) have similar properties. **Periods** (rows) have the same number of electron shells. Key groups: Alkali metals (Group 1), Halogens (Group 17), Noble gases (Group 18).",
  "hydrogen bond": "Hydrogen bonds form when a hydrogen atom bonded to an electronegative atom (N, O, F) is attracted to another electronegative atom. They're weaker than covalent bonds but crucial — they explain why water has a high boiling point and why DNA maintains its double helix structure!",
};

// ─── Voice Commands ───────────────────────────────────────────
export const VOICE_COMMANDS: VoiceCommand[] = [
  { command: "show water molecule", action: "navigate:molecule:water", description: "Opens Water (H₂O) in 3D viewer" },
  { command: "show methane", action: "navigate:molecule:methane", description: "Opens Methane (CH₄) in 3D viewer" },
  { command: "show benzene", action: "navigate:molecule:benzene", description: "Opens Benzene (C₆H₆) in 3D viewer" },
  { command: "show ethanol", action: "navigate:molecule:ethanol", description: "Opens Ethanol in 3D viewer" },
  { command: "start experiment", action: "navigate:lab", description: "Opens Virtual Chemistry Lab" },
  { command: "predict reaction", action: "navigate:predictor", description: "Opens AI Reaction Predictor" },
  { command: "open chat", action: "navigate:tutor", description: "Opens AI Chemistry Tutor" },
  { command: "go home", action: "navigate:home", description: "Returns to Home page" },
  { command: "open dashboard", action: "navigate:dashboard", description: "Opens Dashboard" },
];

// ─── Feature Cards ────────────────────────────────────────────
export const FEATURES = [
  {
    id: "molecule",
    title: "3D Molecule Viewer",
    description: "Explore molecular structures in interactive 3D. Rotate, zoom, and inspect atoms and bonds.",
    gradient: "from-cyan-500 to-blue-600",
    icon: "Atom",
    href: "/molecules",
    badge: "Interactive",
  },
  {
    id: "lab",
    title: "Virtual Chemistry Lab",
    description: "Drag chemicals into virtual beakers and simulate reactions with animated effects.",
    gradient: "from-purple-500 to-pink-600",
    icon: "FlaskConical",
    href: "/lab",
    badge: "Hands-On",
  },
  {
    id: "predictor",
    title: "AI Reaction Predictor",
    description: "Input any reaction and get balanced equations, products, and industrial applications instantly.",
    gradient: "from-emerald-500 to-teal-600",
    icon: "Zap",
    href: "/predictor",
    badge: "AI Powered",
  },
  {
    id: "tutor",
    title: "AI Chemistry Tutor",
    description: "Chat with our AI tutor to learn concepts, solve problems, and deepen your understanding.",
    gradient: "from-orange-500 to-amber-600",
    icon: "Bot",
    href: "/tutor",
    badge: "24/7 Available",
  },
  {
    id: "voice",
    title: "Voice Commands",
    description: "Control ChemFusion hands-free with natural voice commands using your browser's speech API.",
    gradient: "from-pink-500 to-rose-600",
    icon: "Mic",
    href: "/dashboard",
    badge: "Hands-Free",
  },
  {
    id: "dashboard",
    title: "Research Dashboard",
    description: "Track experiments, save predictions, and review your chemistry learning journey.",
    gradient: "from-indigo-500 to-violet-600",
    icon: "LayoutDashboard",
    href: "/dashboard",
    badge: "Analytics",
  },
];

export const STATS = [
  { value: "200+", label: "Molecules Available" },
  { value: "50+", label: "Lab Experiments" },
  { value: "∞", label: "AI Predictions" },
  { value: "24/7", label: "Tutor Access" },
];

export const TESTIMONIALS = [
  {
    name: "Dr. Sarah Chen",
    role: "Chemistry Professor, MIT",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=80&h=80&fit=crop&crop=face",
    text: "ChemFusion AI has transformed how I teach molecular chemistry. The 3D visualizations are incredibly accurate and engaging.",
  },
  {
    name: "Marcus Williams",
    role: "Pre-Med Student",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=80&h=80&fit=crop&crop=face",
    text: "The AI tutor helped me ace my organic chemistry final. It explains complex concepts in a way that actually makes sense!",
  },
  {
    name: "Dr. Priya Patel",
    role: "Research Scientist, Pfizer",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=80&h=80&fit=crop&crop=face",
    text: "The reaction predictor saves hours of literature searching. A must-have tool for any chemistry researcher.",
  },
];
